name: pastis.rb
description: Pastis Ruby Brigade
lang: fr
markdown: redcarpet
highlighter: pygments
paginate: 10
paginate_path: 'page/:num'
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile